### ISSUE TITLE
Dependency on DaisyUI

### ISSUE THREAD

**Issue by J4gQBqqR** [kidonng/unocss-preset-daisy#17]
Hi, sorry if I am confused. But the current dependency graph is like: `this preset -> daisyUI -> tailwindcss`
And it also depends on autoprefixer and postcss.

So when I install the package, tailwind gets installed. How can I ensure myself that I am using unocss on demand instead of tailwind etc.?

**Comment by kidonng** [comment]
This preset uses some internal functions from daisyUI, which does not involve TailwindCSS.

Just because `tailwindcss` is a dependency doesn't mean you are using it. It must be explicitly enabled in PostCSS config to take effect. In other words, if you haven't configured TailwindCSS, you are not using using it.
